package wt.cn.com.wt9.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wt.cn.com.wt9.bean.Work;
import wt.cn.com.wt9.greendao.HeartrateData;

import wt.cn.com.wt9.greendao.WorkDao;
import wt.cn.com.wt9.greendao.HeartrateDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workDaoConfig;
    private final DaoConfig heartrateDataDaoConfig;

    private final WorkDao workDao;
    private final HeartrateDataDao heartrateDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workDaoConfig = daoConfigMap.get(WorkDao.class).clone();
        workDaoConfig.initIdentityScope(type);

        heartrateDataDaoConfig = daoConfigMap.get(HeartrateDataDao.class).clone();
        heartrateDataDaoConfig.initIdentityScope(type);

        workDao = new WorkDao(workDaoConfig, this);
        heartrateDataDao = new HeartrateDataDao(heartrateDataDaoConfig, this);

        registerDao(Work.class, workDao);
        registerDao(HeartrateData.class, heartrateDataDao);
    }
    
    public void clear() {
        workDaoConfig.clearIdentityScope();
        heartrateDataDaoConfig.clearIdentityScope();
    }

    public WorkDao getWorkDao() {
        return workDao;
    }

    public HeartrateDataDao getHeartrateDataDao() {
        return heartrateDataDao;
    }

}
